# @package _group_

query_all:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: #The_path_for_all_query.tsv

query_fold0:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: #The_path_for_query_fold0.tsv

query_fold1:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: #The_path_for_query_fold1.tsv

query_fold2:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: #The_path_for_query_fold2.tsv

query_fold3:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: #The_path_for_query_fold3.tsv

query_fold4:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: #The_path_for_query_fold4.tsv
